### PR TITLE
M->S1 Clarify what "ambassador" means

### PR DESCRIPTION
**Pull request by lc512k**
addresses https://github.com/Financial-Times/engineering-progression/issues/152

### CODE REVIEW

**Comment by Limess** [comment]
I think my main problem with this competency is that I don't find this particularly measurable (aside from word-of-mouth, and who-you-know internal politics which I think we should be discouraging rather than encouraging). I don't think either of these examples address this.

**Comment by lc512k** [comment]
@Limess scrolling through a support channel, for example, a manager could objectively quantify if their report is engaging with people with empathy, thus representing their team in a positive light. The opposite becomes also very evident, when they're completely absent or downright discouraging of the people coming to them for help

**Comment by Limess** [comment]
That's a good example - 'Engages with others with empathy' sounds like a more reasonable target to me than being an 'ambassador' for the team.

**Comment by lc512k** [comment]
On holiday for the next few days, but can pick this up when I'm back, also happy for  anyone else in the group to update

**Comment by alicebartlett** [comment]
These examples are an improvement, and in line with the intention of the competency. More than one person has expressed concern about the term "ambassador" so I think it's worth considering a change to that wording.
On the "internal politics" point, testimony from colleagues is valid evidence against competencies. If you have worked with others they should be able to provide feedback on that interaction.

**Comment by rowanmanning** [comment]
I think this is an improvement, and it's been sitting around for a while so I'd like to get it merged. We're going to do that and have opened another issue (outside of the beta) to further discuss whether "ambassador" is the right word to use.

**Pull request merged**
