### PR TITLE
Rework "communicates tech to non tech" competencies

### LINKED ISSUE #96: Some clarification around technical considerations and stakeholders
_Opened on behalf of @JakeChampion after we ran through the competencies._

---

**Competency:** `f7045590-960d-4a08-b2d6-db6dcff463d6` (S1→S2, Communication)
> When working on a complex problem, is able to break down technical considerations clearly for stakeholders…

Sometimes stakeholders are tech people (as in Origami), which means that this competency seems easier to achieve. Is that OK? Also would an opportunity need to be created for someone to meet this if they're not a tech lead?

### LINKED ISSUE #129: M->S1: Feedback on communicating to non-tech
> Communicates technical concepts to non-technical people clearly

In some, mainly tech-facing teams, formal interaction with non-tech is relatively rare below senior/principal level; compare e.g. an ft.com developer working side by side with designers on a daily basis, and a cloud engineer only dealing with other engineers.

Could the phrasing if this competency by widened to include communicating cross discipline within tech, or communicating with others with less expertise (proto-mentoring)?

From discussion with @ericanand

### PR DESCRIPTION
**Pull request by rowanmanning**
This rewords the "communicates tech to non tech" competencies. I've taken a mix of Sarah and Alice's wording.

This work closes #96, and closes #129

### CODE REVIEW

**Comment by alicebartlett** [comment]
Instead of "less-technical" can we say "colleagues from other disciplines"?

**Comment by alicebartlett** [comment]
This is very relevant: https://github.com/Financial-Times/engineering-progression/issues/129

**Comment by wheresrhys** [comment]
Agree with less technical having implicit meanings. If we have at least one example to cover the case where the other discipline is still technical (e.g. oigami talking to cloud enablement) then I think other disciplines is an improvement

**Comment by rowanmanning** [comment]
Oh, yeah Sarah's suggestion is good. I'll have a go at rewriting these

**Pull request merged**
